### ISSUE TITLE
database

### ISSUE THREAD

**Issue by mohamed-aziz-bennour** [caveatemptors-2015/special-garbanzo#14]
what database we will use: sql postgres
what is a good name for the database?

**Comment by codyhess** [comment]
Yeah, I think Tom wants use postgres.

Let's call the database 'portfolioX'.

**Comment by codyhess** [comment]
Tom said it's fine, and preferred, if we use SQLite, so let's just use the default 'db.sqlite' name. This will make project setup easier too.
