### ISSUE TITLE
login/register redirects to portfolioX

### ISSUE THREAD

**Issue by codyhess** [caveatemptors-2015/special-garbanzo#27]
After logging in or registering, the user should be redirected to the Holdings page.

**Comment by corbyhaas** [comment]
This needs to redirect to the holdings page.

**Comment by codyhess** [comment]
Do this in users/views.py, I think. First users/templates/users/welcome.html needs to call the proper routes for our views.

**Comment by codyhess** [comment]
Aziz finished this.
