### ISSUE TITLE
anybody else see the server yelling for bootstrap and a regex issue?

### ISSUE THREAD

**Issue by Mirabello** [caveatemptors-2015/special-garbanzo#31]
![Uploading Screenshot from 2016-01-02 16:44:53.png…]()

**Comment by codyhess** [comment]
Jared fixed the regex issue. I believe Marc is teaching him to push his own branch to GitHub and make the pull request.

**Comment by codyhess** [comment]
Re-opening this as two separate issues; one for the bootstrap and one for the regex.
